# Generated by Django 5.0.4 on 2024-09-17 00:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="isOffer",
            new_name="is_offer",
        ),
    ]
