# Generated by Django 5.0.4 on 2024-09-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_isoffer_product_is_offer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="isAvailable",
            new_name="is_available",
        ),
        migrations.AddField(
            model_name="product",
            name="sale_rate",
            field=models.IntegerField(default=0, verbose_name="Sale Rate"),
        ),
    ]
