# Generated by Django 5.0.4 on 2024-09-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=200, null=True, verbose_name="Address"),
        ),
    ]
