# Generated by Django 5.0.4 on 2024-09-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Phone number"
            ),
        ),
    ]
