# Generated by Django 5.0.4 on 2024-09-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("wallet", "Wallet"), ("instapay", "Insta Pay")],
                max_length=100,
                verbose_name="Payment Method",
            ),
        ),
    ]
