# Generated by Django 5.0.4 on 2024-10-30 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_remove_salesdata_user_salesdata_user_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesdata",
            name="user_work_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_work_on",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
