# Generated by Django 5.0.4 on 2024-10-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_alter_salesdata_user_work_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesdata",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_contacted", "Not Contacted"),
                    ("not_responding", "Not Responding"),
                    ("refuse", "refuse"),
                    ("thinking", "Thinking"),
                    ("bought", "Bought"),
                ],
                default="not_contacted",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
