# Generated by Django 5.0.4 on 2024-10-25 17:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=50,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="id_card_back",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="id_card_back_image"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="id_card_front",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="id_card_front_image"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="salary",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, null=True, verbose_name="Salary"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("sales", "Sales"),
                    ("accountant", "Accountant"),
                    ("storage", "Storage"),
                    ("moderator", "Moderator"),
                ],
                default="customer",
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
