# Generated by Django 5.0.4 on 2024-10-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_gender_user_id_card_back_user_id_card_front_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("banned", "Banned"),
                    ("active", "Active"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
