# Generated by Django 5.0.4 on 2024-10-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Password",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                ("key", models.CharField(max_length=250, verbose_name="Key")),
                ("password", models.CharField(max_length=250, verbose_name="password")),
            ],
            options={
                "verbose_name": "Password",
                "verbose_name_plural": "Passwords",
            },
        ),
    ]
