# Generated by Django 5.0.4 on 2024-09-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone_number",
                    models.CharField(max_length=100, verbose_name="Phone number"),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mail",
                "verbose_name_plural": "Mails",
            },
        ),
    ]
