# Generated by Django 5.0.4 on 2024-10-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mail",
            name="isRead",
            field=models.BooleanField(default=False, verbose_name="Is Read"),
        ),
    ]
